### PR TITLE
Allowing to override default lexer, parser and compiler on ExpressionLanguage subclasses

### PR DESCRIPTION
**Pull request by yamek**

### CODE REVIEW

**Comment by fabpot** [comment]
:-1: The lack of interfaces was done on purpose. The only extension point we provide is functions and to keep the expression language the same for everyone, we disallow changes to the Lexer, Parser, Compiler.

What would be your use case?

**Comment by yamek** [comment]
I want to use the component's core classes to compile into another language. So I need to extend the ExpressionLanguage class and use a custom compiler. Are you planning to support this on some close future version?

**Comment by bourvill** [comment]
i need the same feature.

In my case, i need to create new Parser for extend a new Expression mapping for exemple : 
```php
    [
        'inf'   => '<',
        'infeg' => '<=',
        'sup'   => '>',
        'supeg' => '>=',
        'eg'    => '==',
        'diff'  => '!=',
    ]
```

**Comment by yobrx** [comment]
+1

**Pull request closed without merging**
